name: Java CI with Maven and Docker

on:
    push:
        branches:
            - 'master'
    pull_request:
        branches:
            - 'master'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven

            - name: Build with Maven
              run: mvn -B package --file CI_CDpipeline/pom.xml

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: user/app:latest

    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven

            - name: Run Tests
              run: mvn test --file CI_CDpipeline/pom.xml

    deploy:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Pull Docker image
              run: docker pull user/app:latest

            - name: Deploy Docker container
              run: docker run -p 8080:8080 -d user/app:latest
