name: Java CI with Maven

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven
            - name: Compile with Maven
              run: mvn -B clean compile --file pom.xml
            - name: Test with Maven
              run: mvn -B test --file pom.xml

    test: # Optional test job
        runs-on: ubuntu-latest
        needs: build # This job depends on the build completing successfully
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven
            - name: Run additional tests (if needed)
              run: mvn -B test -Dtest=your.specific.test.class # Customize as needed

    deploy: # Optional deploy job
        runs-on: ubuntu-latest
        needs: build # This job depends on the build completing successfully
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven
            - name: Build with Maven (if needed)
              run: mvn -B package --file pom.xml # Skip if already done in build job
            - name: Deploy to target environment (e.g., AWS, Azure)
              uses: example-deployment-action@v1 # Replace with your deployment action
