name: Java CI with Maven

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven
            - name: Build with Maven
              run: mvn -B package --file pom.xml

            # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
            - name: Update dependency graph
              uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven
            - name: Run Tests
              run: mvn test --file pom.xml

    deploy:
        runs-on: ubuntu-latest
        needs: test

        # steps:
        # - name: Deploy to production
        # Add your deployment steps here, e.g., deploying to a server or a cloud platform
